name: Build and Analyze

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven

    - name: Build with Maven
      run: mvn clean verify

    - name: Run SonarCloud Analysis
      run: mvn verify sonar:sonar \
            -Dsonar.projectKey=jfragoso_quarkus-demo \
            -Dsonar.organization=jfragoso \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.java.binaries=target/classes
          
    - name: Wait for SonarCloud Quality Gate
      uses: sonarsource/sonarcloud-quality-gate-action@v1.1.0
      with:
        projectKey: jfragoso_quarkus-demo
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Crear issue si Quality Gate falla
      if: failure()
      uses: peter-evans/create-issue-from-file@v4
      with:
        title: 🚨 Falla en SonarCloud - Quality Gate Reprobado
        content-file: .github/sonar-alert.md
        labels: seguridad, calidad, sonarcloud


